version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Running Maven build in the root directory"
      - pwd
      - ls -l
      - mvn clean package -Dspring.profiles.active=test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
    - buildspec.yml
  discard-paths: yes