version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "📁 CodeBuild source directory: $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo "📍 Now in: $(pwd)"
      - ls -l
      - mvn test -Dspring.profiles.active=test
      - mvn package -Dmaven.test.skip=true

  post_build:
    commands:
      - echo "✅ Build completed on $(date)"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
