version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build completed on `date`
      - mvn test -Dspring.profiles.active=test
      - mvn package -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes