version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Current directory: $(pwd)"
      - echo "CodeBuild source directory: $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - ls -l
      - mvn clean package -Dspring.profiles.active=test

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - target/*.jar
    - buildspec.yml
  discard-paths: yes
